services:
  clawsearch-redis:
    container_name: clawsearch-redis
    image: redis:alpine
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
    networks:
      - clawsearch-network
    restart: unless-stopped

  clawsearch-searxng:
    container_name: clawsearch-searxng
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SEARXNG_VERSION: ${SEARXNG_VERSION}
    networks:
      - clawsearch-network
    depends_on:
      - clawsearch-redis
    volumes:
      - ./customizations/config/settings.yml:/etc/searxng/settings.yml:rw
    environment:
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY}
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL}
      - SEARXNG_REDIS_URL=redis://:${REDIS_PASSWORD}@clawsearch-redis:6379/0
      - SEARXNG_SETTINGS_PATH=/etc/searxng/settings.yml
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: unless-stopped

  clawsearch-nginx:
    container_name: clawsearch-nginx
    image: nginx:alpine
    networks:
      - clawsearch-network
    depends_on:
      - clawsearch-searxng
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETUID
      - SETGID
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"
    restart: unless-stopped

networks:
  clawsearch-network:
    external: true

volumes:
  redis-data:
